sudo: required

language: generic

services:
  - docker
 
before-install:
  - docker build -t devil/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true devil/docker-react npm run test
